// Generate supabase/seed.sql from lib/seed-content.ts.
//
// Run with:  npx tsx scripts/generate-seed-sql.ts
//
// The output file should be checked in. After running migrations on a fresh
// Supabase project, paste seed.sql into the SQL Editor (or use the Supabase
// CLI) to populate the initial real interview articles.
//
// Per docs/borderless-habitat-plan.md §9.2, posts ship with author_id = null
// and author_display_name set; an admin re-attributes them once Sonya / 長晉
// register real accounts.

import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { seedPosts, type SeedPost } from "../lib/seed-content"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const OUTPUT_PATH = resolve(__dirname, "..", "supabase", "seed.sql")

function escapeSqlString(value: string): string {
  return value.replace(/'/g, "''")
}

function asTextLiteral(value: string | null): string {
  if (value === null) return "null"
  return `'${escapeSqlString(value)}'`
}

function asTimestampLiteral(value: string): string {
  return `'${escapeSqlString(value)}'::timestamptz`
}

function asTextArrayLiteral(values: string[]): string {
  if (values.length === 0) return "'{}'::text[]"
  const inner = values
    .map((item) => `"${item.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`)
    .join(",")
  return `'{${inner}}'::text[]`
}

function buildPostInsert(post: SeedPost): string {
  const columns = [
    "type",
    "title",
    "slug",
    "content",
    "html_content",
    "excerpt",
    "country_slug",
    "tags",
    "status",
    "author_id",
    "author_display_name",
    "created_at",
    "updated_at",
  ].join(", ")

  const values = [
    asTextLiteral(post.type),
    asTextLiteral(post.title),
    asTextLiteral(post.slug),
    asTextLiteral(post.content),
    asTextLiteral(post.html_content),
    asTextLiteral(post.excerpt),
    asTextLiteral(post.country_slug),
    asTextArrayLiteral(post.tags),
    asTextLiteral(post.status),
    "null",
    asTextLiteral(post.author_display_name),
    asTimestampLiteral(post.created_at),
    asTimestampLiteral(post.updated_at),
  ].join(",\n  ")

  return `insert into public.posts (${columns}) values (\n  ${values}\n) on conflict (slug) do update set\n  title = excluded.title,\n  content = excluded.content,\n  html_content = excluded.html_content,\n  excerpt = excluded.excerpt,\n  country_slug = excluded.country_slug,\n  tags = excluded.tags,\n  status = excluded.status,\n  author_display_name = excluded.author_display_name,\n  updated_at = excluded.updated_at;`
}

function buildSeedSql(): string {
  const header = [
    "-- Auto-generated by scripts/generate-seed-sql.ts.",
    "-- Source: lib/seed-content.ts. Edit the source, do not edit this file.",
    "-- Run: npx tsx scripts/generate-seed-sql.ts",
    "",
  ].join("\n")

  const body = seedPosts.map(buildPostInsert).join("\n\n")

  return `${header}\n${body}\n`
}

function main(): void {
  const sql = buildSeedSql()
  writeFileSync(OUTPUT_PATH, sql, "utf8")
  process.stdout.write(`Wrote ${seedPosts.length} posts to ${OUTPUT_PATH}\n`)
}

main()
